global:
  subscriptionName: "Compliance_Tools_Eng"
  resourceGroup:
    name: compes-bedrock-lab
    location: westus2
gitRepo:
  teamOrUser: smartpcr
  name: git-deploy
  deployPrivateKey: flux-deploy-key
  deployPublicKey: flux-deploy-pub
kv:
  name: compes-bedrock-kv
  reader: compes-bedrock-kv-reader
terraform:
  clientAppName: compes-bedrock-terraform-spn
  clientSecret: compes-bedrock-terraform-spn-pwd
  backend:
    storageAccount: compesterraformstate
    containerName: compes
    key: tfstate
aks:
  reuseExistingAadApp: true
  serverApp: App Center AKS AAD (non-production)
  serverSecret: AppCenter-AKS-AADAppPwd
  clientApp: App Center AKS (non-production)
  clusterName: compes-bedrock-lab
  nodeCount: 3
  vmSize: "Standard_D4s_v3"
  dnsPrefix: bedrock-lab
  virtualNetwork: bedrock-vnet
  ssh:
    privateKey: "compes-bedrock-aks-ssh-key"
    publicKey: "compes-bedrock-aks-ssh-pub"
    privateKeyPwd: "compes-bedrock-aks-ssh-key-pwd"
  owners:
    - name: xiaodoli@microsoft.com
      type: user
  contributors:
    - name: "Compliance Tooling Team"
      type: group
  readers:
    - name: "1cs dri"
      type: group
acr:
  name: compesbedrockacr
  email: xiaodoli@microsoft.com
  auth_secret: compes-bedrock-acr-auth
dns:
  name: dev.1es.io
  caaIssuer: letsencrypt.org # use microsoft when CA is internal
cosmosdb:
  account: compes-bedrock-lab
  authKey: compes-bedrock-lab-authkey
  consistency: Strong
  failOverRegion: eastus
  enableFirewallRules: false
  corpIpRanges: 24.17.206.116
  api: SQL
  db: product-catalog
  collections:
    - name: "policy-ado-snapshot"
      partition: "/partitionKey"
      throughput: 1000
    - name: "policy-catalog"
    - name: "policy-events"
      partition: "/partitionKey"
    - name: "policy-events-error"
      partition: "/partitionKey"
    - name: "policy-events-lease"
    - name: "policy-extension"
      partition: "/partitionKey"
    - name: "policy-install"
      partition: "/partitionKey"
    - name: "policy-installerror"
      partition: "/partitionKey"
    - name: "policy-refresh"
      partition: "/partitionKey"
    - name: "policy-refresh-error"
      partition: "/partitionKey"
    - name: "policy-refresh-lease"
    - name: "policy-snapshots"
      partition: "/partitionKey"
      throughput: 1000
    - name: "policy-snapshots-error"
      partition: "/partitionKey"
    - name: "policy-snapshots-lease"
    - name: "policy-subscription-registry"
      partition: "/id"
    - name: "policy-catalog"
    - name: "products"
    - name: "ps"
      partition: "/partitionKey"
    - name: "ps-lease"
      partition: "/id"
appInsights:
  name: compes-bedrock-ai