global:
  subscriptionName: "RRD MSDN Premium"
  resourceGroup:
    name: rrdp-bedrock-lab
    location: westus2
gitRepo:
  teamOrUser: smartpcr
  name: flux-get-started
  deployPrivateKey: flux-deploy-key
  deployPublicKey: flux-deploy-pub
kv:
  name: rrdp-bedrock-kv
terraform:
  clientAppName: rrdp-bedrock-terraform-spn
  clientSecret: rrdp-bedrock-terraform-spn-pwd
aks:
  reuseExistingAadApp: true
  serverApp: rrdp-bedrock-aks-server-app
  serverSecret: rrdp-bedrock-aks-spn-pwd
  clientApp: rrdp-bedrock-aks-client-app
  clusterName: rrdp-bedrock-lab
  nodeCount: 2
  vmSize: "Standard_D2s_v3"
  dnsPrefix: bedrock-lab
  virtualNetwork: bedrock-vnet
  ssh:
    privateKey: "rrdp-bedrock-aks-ssh-key"
    publicKey: "rrdp-bedrock-aks-ssh-pub"
    privateKeyPwd: "rrdp-bedrock-aks-ssh-key-pwd"