global:
  subscriptionName: "RRD MSDN Ultimate"
  resourceGroup:
    name: rrdu-bedrock-lab
    location: westus2
gitRepo:
  teamOrUser: smartpcr
  name: git-deploy
  sshUrl: git@github.com:smartpcr/git-deploy.git
  deployPrivateKey: flux-deploy-key
  deployPublicKey: flux-deploy-pub
kv:
  name: rrdu-bedrock-kv
  reader: rrdu-bedrock-kv-reader
terraform:
  clientAppName: rrdu-bedrock-terraform-spn
  clientSecret: rrdu-bedrock-terraform-spn-pwd
  backend:
    storageAccount: rrdpterraformstate
    containerName: rrdp
    key: tfstate
aks:
  reuseExistingAadApp: true
  serverApp: rrdu-bedrock-aks-server-app
  serverSecret: rrdu-bedrock-aks-spn-pwd
  clientApp: rrdu-bedrock-aks-client-app
  clusterName: rrdu-bedrock-lab
  nodeCount: 2
  vmSize: "Standard_D2s_v3"
  dnsPrefix: rrdu
  virtualNetwork: rrdu-bedrock-lab-vnet
  ssh:
    privateKey: "rrdu-bedrock-aks-ssh-key"
    publicKey: "rrdu-bedrock-aks-ssh-pub"
    privateKeyPwd: "rrdu-bedrock-aks-ssh-key-pwd"
acr:
  name: rrdubedrockacr
  email: lingxd@gmail.com
  auth_secret: rrdu-bedrock-acr-auth
dns:
  name: dev.1es.io
  caaIssuer: letsencrypt.org # use microsoft when CA is internal
appInsights:
  name: rrdu-bedrock-ai
  secrets:
    instrumentationKey: rrdu-bedrock-ai-instrumentation-key
    appId: rrdu-bedrock-ai-app-id