backup:
  subscription: Compliance_Tools_Eng
  vaultName: xiaodong-kv
  acrName: xiaodongacr
secrets:
  - AdoOrgApi-Certificate
  - Geneva-Certificate
  - KeyVault-Certificate
  - onees-dev-docdb-key
  - OneesExtensionManager-Certificate
  - Policy-Certificate
  - ProductCatalog-Certificate
  - ProductCatalog-DocumentDBKey
  - ProductCatalog-Redis-AccessKey
  - ProductCatalog-SP-App-Key
  - sace-acr-spn-pwd
  - Ssl-Aks-Default-Certificate
  - Ssl-Certificate
